# Generated by Django 6.0.3 on 2026-05-11 22:05

import uuid

import django.utils.timezone
from django.db import migrations, models


def default_work_schedule():
    return {
        "monday": {"enabled": True, "slots": [{"start": "09:00", "end": "18:00"}]},
        "tuesday": {"enabled": True, "slots": [{"start": "09:00", "end": "18:00"}]},
        "wednesday": {"enabled": True, "slots": [{"start": "09:00", "end": "18:00"}]},
        "thursday": {"enabled": True, "slots": [{"start": "09:00", "end": "18:00"}]},
        "friday": {"enabled": True, "slots": [{"start": "09:00", "end": "15:00"}]},
        "saturday": {"enabled": False, "slots": []},
        "sunday": {"enabled": False, "slots": []},
    }


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Asesor", "Asesor"),
                            ("Autónomo", "Autónomo"),
                            ("Sociedad", "Sociedad"),
                        ],
                        default="Autónomo",
                        max_length=50,
                    ),
                ),
                ("specialties", models.JSONField(blank=True, default=list)),
                (
                    "profile_image",
                    models.FileField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("work_start", models.TimeField(blank=True, null=True)),
                ("work_end", models.TimeField(blank=True, null=True)),
                (
                    "work_schedule",
                    models.JSONField(blank=True, default=default_work_schedule),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
