# Generated by Django 6.0.3 on 2026-05-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_groups_alter_user_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_on_vacation",
            field=models.BooleanField(default=False),
        ),
    ]
