# Generated by Django 6.0.3 on 2026-04-27 22:26

import uuid

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "conversations",
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content_snippet", models.TextField()),
                ("page_number", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "document_chunks",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("User", "User"), ("Assistant", "Assistant")],
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "messages",
            },
        ),
        migrations.CreateModel(
            name="VectorStore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
            ],
            options={
                "db_table": "vector_store",
            },
        ),
    ]
