# Generated by Django 6.0.3 on 2026-06-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0004_conversation_conversation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="unread_alerts",
            field=models.BooleanField(default=False),
        ),
    ]
