# Generated by Django 6.0.3 on 2026-05-11 22:05

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_tax_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="EUR", max_length=10)),
                ("operation_date", models.DateField(blank=True, null=True)),
                ("serie", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "last_invoice_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "nif_tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NIF", "NIF"),
                            ("CIF", "CIF"),
                            ("NIE", "NIE"),
                            ("PASAPORTE", "Pasaporte"),
                            ("IVA", "IVA Intracomunitario"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "nif_codigo_pais",
                    models.CharField(blank=True, default="ES", max_length=2, null=True),
                ),
                (
                    "nif_identificacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "clave_operacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "01 - Operación general"),
                            ("02", "02 - Exportación"),
                            ("03", "03 - Intracomunitaria"),
                            ("04", "04 - Operación exenta"),
                            ("05", "05 - Inversión sujeto pasivo"),
                        ],
                        default="01",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "equivalence_tax_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "equivalence_tax_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "db_table": "invoice_data",
            },
        ),
        migrations.CreateModel(
            name="TaxCalendar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("IVA", "IVA"),
                            ("IRPF", "IRPF"),
                            ("Impuesto de Sociedades", "Impuesto de Sociedades"),
                            ("Retenciones", "Retenciones"),
                            ("Pagos a Cuenta", "Pagos a Cuenta"),
                            ("Aduanas", "Aduanas"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("Mensual", "Mensual"),
                            ("Trimestral", "Trimestral"),
                            ("Semestral", "Semestral"),
                            ("Anual", "Anual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("deadline", models.DateField(db_index=True)),
                ("is_presented", models.BooleanField(db_index=True, default=False)),
                ("presented_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Tax Calendars",
                "db_table": "tax_calendar",
                "ordering": ["-deadline"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=500)),
                ("storage_path", models.CharField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Validado", "Validado"),
                            ("Procesado", "Procesado"),
                            ("Rechazado", "Rechazado"),
                            ("Error", "Error"),
                        ],
                        default="Pendiente",
                        max_length=50,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("Factura", "Factura"),
                            ("Gasto", "Gasto"),
                            ("Ingreso", "Ingreso"),
                        ],
                        max_length=50,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="business.business",
                    ),
                ),
            ],
            options={
                "db_table": "documents",
            },
        ),
    ]
