# Generated by Django 6.0.3 on 2026-05-11 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0002_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoicedata",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_data",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="taxcalendar",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_calendar",
                to="business.business",
            ),
        ),
        migrations.AddIndex(
            model_name="taxcalendar",
            index=models.Index(
                fields=["business", "tax_type", "period_start"],
                name="tax_calenda_busines_0becda_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxcalendar",
            index=models.Index(
                fields=["business", "is_presented", "deadline"],
                name="tax_calenda_busines_c89281_idx",
            ),
        ),
    ]
