# Generated by Django 6.0.3 on 2026-05-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_update_status_and_tax_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[("Pendiente", "Pendiente"), ("Procesado", "Procesado")],
                default="Pendiente",
                max_length=50,
            ),
        ),
    ]
