# Generated by Django 6.0.3 on 2026-05-30 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_document_status"),
        ("business", "0004_add_responsible_advisor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("En cola", "En cola"),
                    ("Pendiente", "Pendiente"),
                    ("Procesado", "Procesado"),
                    ("Error", "Error"),
                ],
                default="En cola",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="taxcalendar",
            name="presented_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taxcalendar",
            name="presented_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="presented_tax_calendars",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
