# Generated by Django 6.0.3 on 2026-04-27 22:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("tax_id", models.CharField(max_length=100, unique=True)),
                ("sector", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "business",
            },
        ),
        migrations.CreateModel(
            name="UserBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_in_business",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Editor", "Editor"),
                            ("Viewer", "Viewer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="business.business",
                    ),
                ),
            ],
            options={
                "db_table": "user_business",
            },
        ),
    ]
