# Generated by Django 6.0.3 on 2026-05-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["tax_status"], name="business_tax_sta_06f19d_idx"
            ),
        ),
    ]
