# Generated by Django 6.0.3 on 2026-05-30 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_business_business_tax_sta_06f19d_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="responsible_advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_businesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["responsible_advisor"],
                name="business_resp_advisor_idx",
            ),
        ),
    ]
