# Generated by Django 6.0.3 on 2026-05-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0004_add_responsible_advisor"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="business",
            new_name="business_respons_5135e0_idx",
            old_name="business_resp_advisor_idx",
        ),
    ]
